### ISSUE TITLE
AdoptOpenJDK: fetching fails for deprecated api v2 => v3 should be used instead

### ISSUE THREAD

**Issue by lask79** [lean-delivery/ansible-role-java#116]
### SUMMARY

For some time the API for AdoptOpenJDK has been deprecated in the version v2. The v3 should be used instead.
Some calls for JDK 8 are not working anymore with v2.

##### ISSUE TYPE
 - Bug Report

I already created a PR for this: #115

**Comment by rockdreamer** [comment]
Thank you for investigating and providing a fix for this issue @lask79 ! 
I've got a few deployments blocked because of this.

**Comment by rockdreamer** [comment]
Hi, it looks like the proposed change was not enough. Please check and apply #118
