### ISSUE TITLE
7.1.1 not published to galaxy

### ISSUE THREAD

**Issue by dzmitry-rudnouski** [lean-delivery/ansible-role-java#137]
##### SUMMARY
Version 7.1.1 is not published to galaxy

##### ISSUE TYPE
 - Bug Report

**Comment by roumano** [comment]
sadly same issue with the `v7.2.0` version

**Comment by pavelpikta** [comment]
All missed versions were publish into ansible-galaxy 
![image](https://github.com/lean-delivery/ansible-role-java/assets/9392033/c11a108c-b214-4f8d-bebf-bf148b6df20c)
