### ISSUE TITLE
Error setting alternatives while JRE provisioning

### ISSUE THREAD

**Issue by Kuzmin-Dmitry** [lean-delivery/ansible-role-java#23]
##### SUMMARY
The role tries to set alternatives for modules that are in JDK but which are not JRE

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
TASK [lean_delivery.java : Update alternatives]

##### OS / ENVIRONMENT
CentOS 7.4

##### STEPS TO REPRODUCE
Set transport_web : "http://{{ storage_name }}/jre-8u181-linux-x64.tar.gz"

##### EXPECTED RESULTS
TASK [lean_delivery.java : Update alternatives] 
ok: [aux1] => (item=java)
failed: [aux1] (item=javac) => {"binary": "javac", "changed": false, "msg": "Specified path /opt/jre/jre1.8.0_181/bin/javac does not exist"}
failed: [aux1] (item=jar) => {"binary": "jar", "changed": false, "msg": "Specified path /opt/jre/jre1.8.0_181/bin/jar does not exist"}

##### ACTUAL RESULTS
Add javac and jar existence validation

**Comment by anastacia-maletskaya-epam** [comment]
Fix was merged
