### ISSUE TITLE
Add java unlimited security policy

### ISSUE THREAD

**Issue by ViachaslauKabak** [lean-delivery/ansible-role-java#30]
##### ISSUE TYPE
 - Feature Idea

##### ANSIBLE VERSION

```

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by ibarysev** [comment]
Merged to master - https://github.com/lean-delivery/ansible-role-java/pull/31

**Comment by tgadiev** [comment]
Closing as fixed
