### ISSUE TITLE
Testinfra test fails for package install on Ubuntu 18

### ISSUE THREAD

**Issue by tgadiev** [lean-delivery/ansible-role-java#51]
##### SUMMARY
Testinfra test reports failure after installation of Java 11 deb package on Ubuntu 18

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
testinfra test

##### ANSIBLE VERSION
```
ansible 2.5.14
  config file = None
  configured module search path = [u'/home/gitlab-runner/.local/lib/python2.7/site-packages/epam_ansible']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, Aug 16 2018, 14:17:09) [GCC 6.4.0]
```

##### CONFIGURATION
$ ansible --version
ansible 2.5.14
  config file = None
  configured module search path = [u'/home/gitlab-runner/.local/lib/python2.7/site-packages/epam_ansible']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, Aug 16 2018, 14:17:09) [GCC 6.4.0]
$ molecule --version
molecule, version 2.19.1.dev120

##### OS / ENVIRONMENT
Ubuntu 18.04

##### STEPS TO REPRODUCE
See the following job:
https://gitlab.com/lean-delivery/ansible-role-java/-/jobs/165557410

##### EXPECTED RESULTS
Like this one:
https://gitlab.com/lean-delivery/ansible-role-java/-/jobs/165557408

##### ACTUAL RESULTS
```
    =================================== FAILURES ===================================
    _ test_java_version[ansible://test-aws-ubuntu18-ansible-role-java-11-otn-deb] __
    
    host = <testinfra.host.Host object at 0x7f2a88853bd0>
    
        def test_java_version(host):
            command = host.run('java -version')
    >       assert command.rc == 0
    E       AssertionError: assert 127 == 0
    E        +  where 127 = CommandResult(command='java -version', exit_status=127, stdout=u'', stderr=u'/bin/sh: 1: java: not found').rc
    
    ../resources/tests/test_default.py:19: AssertionError
    ====================== 1 failed, 7 passed in 7.70 seconds ======================
```

**Comment by azeliashchonak** [comment]
@tgadiev This test is correct when python run "java -version" it should get 0 as exit code of the command (without errors), but it gets exit code 127, so this issue related to java setup.  Code 127 command not found in PATH and it is not a built-in shell command.

**Comment by tgadiev** [comment]
Fixed by https://github.com/lean-delivery/ansible-role-java/pull/55
