### ISSUE TITLE
Win-Chocolatey paid functions

### ISSUE THREAD

**Issue by Densoff** [lean-delivery/ansible-role-java#58]
According [https://chocolatey.org/docs/how-to-parse-package-parameters-argument](https://chocolatey.org/docs/how-to-parse-package-parameters-argument) `package_params` in module `win_chocolatey` not for free using. Need to check does it work correctly in  ansible-role-java/tasks/Windows/chocolatey.yml

**Comment by pavelpikta** [comment]
Not relevant. Package params are removed
