### ISSUE TITLE
Zulu-fallback transport 

### ISSUE THREAD

**Issue by pavelpikta** [lean-delivery/ansible-role-java#84]
##### SUMMARY

Need update zulu fallback transport to use API https://zulu.api.azul.com

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

zulu-fallback transport

**Comment by EliasGabrielsson** [comment]
Checkout this cURL request to fetch all available `.tar` packages for all zulu versions:

```
curl 'https://www.azul.com/wp-admin/admin-ajax.php' -H 'Accept: */*' -H 'X-Requested-With: XMLHttpRequest' -H 'Content-Type: multipart/form-data; boundary=---------------------------17447165291708986765346780730' -H 'Connection: keep-alive' -H 'Cache-Control: max-age=0' -H 'TE: Trailers' --data-binary $'-----------------------------17447165291708986765346780730\r\nContent-Disposition: form-data; name="action"\r\n\r\nbundles_filter_query\r\n-----------------------------17447165291708986765346780730\r\nContent-Disposition: form-data; name="action"\r\n\r\nsearch_bundles\r\n-----------------------------17447165291708986765346780730--\r\n'
```

Sorry for writing a long oneliner. Exported from Firefox auto cURL generator tool and cleaned away my cookies.

**Comment by pavelpikta** [comment]
> Checkout this cURL request to fetch all available `.tar` packages for all zulu versions. It dumps a JSON array.
> 
> ```
> curl 'https://www.azul.com/wp-admin/admin-ajax.php' -H 'Accept: */*' -H 'X-Requested-With: XMLHttpRequest' -H 'Content-Type: multipart/form-data; boundary=---------------------------17447165291708986765346780730' -H 'Connection: keep-alive' -H 'Cache-Control: max-age=0' -H 'TE: Trailers' --data-binary $'-----------------------------17447165291708986765346780730\r\nContent-Disposition: form-data; name="action"\r\n\r\nbundles_filter_query\r\n-----------------------------17447165291708986765346780730\r\nContent-Disposition: form-data; name="action"\r\n\r\nsearch_bundles\r\n-----------------------------17447165291708986765346780730--\r\n'
> ```
> 
> Sorry for writing a long oneliner. Exported from Firefox auto cURL generator tool and cleaned away my cookies.

Thank for this. I try to implement this with ansible win_uri module
