### ISSUE TITLE
Add support of Amazon Corretto install

### ISSUE THREAD

**Issue by tgadiev** [lean-delivery/ansible-role-java#95]
##### SUMMARY
Need to implement fallback transport to download and install [Amazon Corretto Java](https://aws.amazon.com/corretto/?utm_source=jdkdev&utm_medium=download)

##### ISSUE TYPE
 - Feature Idea

**Comment by dzmitry-rudnouski** [comment]
@tgadiev 
Here is code example for Linux 64 that could be extended for other OS
`
- name: test
  hosts: localhost
  vars:
    ns: http://www.w3.org/1999/xhtml
    java_major_version: 8
    download_page: "https://docs.aws.amazon.com/corretto/latest/corretto-{{ java_major_version }}-ug/downloads-list.html"
  tasks:
    - name: Install lxml
      pip:
        name: lxml

    - name: Get download html
      uri:
        url: "{{ download_page }}"
        return_content: true
      register: html

    - set_fact:
        os: "{{ ansible_facts.system | lower }}"
      
    - set_fact:
        arch: 'x64'
      when: ansible_architecture == "x86_64"

    - name: Read attribute value
      xml:
        xmlstring: "{{ html.content }}"
        namespaces:
          ns: "{{ ns }}"
        xpath: //ns:a[text()[contains(., '{{ os }}-{{ arch }}.tar.gz')]]
        content: attribute
        attribute: href
      register: html_value

    - set_fact:
        url_key: "{{ '{' + ns + '}a' }}"

    - name: Download
      uri:
        url: "{{ html_value.matches[0][url_key].href }}"
        dest: .
`
